apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-e4vu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-e4vu
    app.kubernetes.io/part-of: tkrw-pr714-0075-0052-app
  name: devfile-sample-e4vu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-e4vu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-e4vu
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0052-tenant/tkrw-pr714-0075-0052-app/devfile-sample-e4vu@sha256:47553f4cc8dddded0509a84c804d58d584630ee264f1a04a7d3eda940216c49d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
